### ISSUE TITLE
Seems to be incompatible with glass8.eu

### ISSUE THREAD

**Issue by Darthagnon** [spitfirex86/ClassicThemeTray#1]
I've got an aero glass mod installed for Win10 - it seems to be incompatible with this. 
(more info on the mod: http://www.glass8.eu/)

I'd hoped that running this would replace the aero effect when active, and restore the aero effect when disabled.

**Comment by spitfirex86** [comment]
Glass8 hooks DWM functions to draw its own window frame instead of default system ones. It's not something I can easily toggle. Perhaps you should request a quick tray toggle as a feature from the Glass8 developer.
