### ISSUE TITLE
About the color of the title bar

### ISSUE THREAD

**Issue by umbrella-k** [spitfirex86/ClassicThemeTray#4]
I liked the old Classic theme because of the rich colors of Windows.
Is there any way to recreate it?
My current situation↓.
![image](https://user-images.githubusercontent.com/68675858/153702621-d104dc89-d0a9-482f-9d28-89db8bfe2745.png)
I want to do this↓.
![image](https://user-images.githubusercontent.com/68675858/153702951-93d927ff-7b02-4d39-ada1-4941e2d0dd3b.png)

Or is there an entry in the registry to change the color?

Also, do you plan to add a setting to exclude only certain processes?

And since I'm Japanese and not good at English, I use Deepl translation.

**Comment by OrthodoxWindows** [comment]
You must configure the colors.
Use that : https://github.com/WinClassic/SimpleClassicTheme/blob/master/SimpleClassicTheme/Resources/deskn.cpl
Or that : https://github.com/Superfly-Inc/SMACC
Or that : https://archive.org/details/themak5_3

**Comment by umbrella-k** [comment]
thank you
